# build d'une image puis push sur le docker hub via var d'env github

name: Build Docker Images
on:
  push:
    branches:
      - dev
jobs:
  push_to_registries:
    name: Push Docker image on Docker Hub registery
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Extract metadata tags for Docker Hub
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{secrets.DOCKER_HUB_USERNAME}}/identity-store
          tags: |
            type=raw, value=${{ github.ref_name }}-latest
            type=sha, prefix=${{ github.ref_name}}-

      - name: Pushing Image on Docker Hub
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 58237
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SERVER_USER }}/srv/app/dev"

      - name: Deploy App on Serveur
        id: deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 58237
          script: |
            cd /home/${{ secrets.SERVER_USER }}/srv/app/dev

            docker compose pull

            docker compose up -d
